name: Mento CI/CD to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                  
  ECR_REPOSITORY: mento-backend          

jobs:
  build-and-deploy:
    name: Build & Push to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Force LFS Pull and Verify Sizes
        run: |
          git lfs pull
          echo "Checking file sizes before building Docker..."
          ls -lh models/module1/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }} 
          LATEST_TAG: latest           
        run: |
          docker build -t $REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG -t $REGISTRY/${{ env.ECR_REPOSITORY }}:$LATEST_TAG .
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
          docker push $REGISTRY/${{ env.ECR_REPOSITORY }}:$LATEST_TAG